export const CHANGE_CURRENT_STEP = 'CHANGE_CURRENT_STEP';
export const CHANGE_SEND_AS_DROPSHIPPER = 'CHANGE_SEND_AS_DROPSHIPPER';

export const SELECT_SHIPMENT_METHOD = 'SELECT_SHIPMENT_METHOD';
export const SELECT_PAYMENT_METHOD = 'SELECT_PAYMENT_METHOD';

export const GET_TOTAL_BILL = 'GET_TOTAL_BILL';
export const ADD_TO_TOTAL_BILL = 'ADD_TO_TOTAL_BILL';
export const SUBTRACT_FROM_TOTAL_BILL = 'SUBTRACT_FROM_TOTAL_BILL';